name: Deploy Laravel to DigitalOcean

on:
  push:
    branches:
      - main  # Déclencher l'action sur chaque push dans la branche 'main'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        cp .env.example .env
        php artisan key:generate

    - name: Ensure Repository Cloned
      run: |
        if [ ! -d "/var/www/laravel/.git" ]; then
         git clone https://github.com/Bayekula-hb/nganda-api.git /var/www/laravel
        fi

    - name: Deploy to DigitalOcean
      run: |
            cd /var/www/laravel
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan config:cache
